### ISSUE TITLE
Videos are not working properly on mobiles

### ISSUE THREAD

**Issue by OsamaFelFel** [Truman-State-University/truman-digital-sign-theme#3]
Great work with this theme, we rally liked it.

Videos are not being played on mobiles. It only shows the preview image and nothing happen till it gets swapped. We tested it on iPhone using Safari, FireFox and Chrome and we can't figure the problem.

**Comment by mogmarsh** [comment]
Thanks for the feedback. iOS can only play videos without user interaction if they have no audio track or are muted, and they have to have the playsinline parameter set. I changed the theme to mute all videos by default (including YouTube), but I added checkboxes to enable sound. For it to work on iOS, you will not want to enable sound for any of your videos.
This is fixed in version 1.1.3
